Feature/home
mju-likelion/raonair-frontend pull request #2
Opened 2021-08-30 07:41 UTC by Bhanjo

2021-09-10 18:01 UTC, ndaemy commented
풀리퀘 이름은 "어떤 기능" 이런 식이 좋습니당

2021-09-10 18:06 UTC, ndaemy requested changes

2021-09-10 18:06 UTC, ndaemy commented on .prettierrc
> +}
으악

2021-09-10 18:06 UTC, ndaemy commented on components/PlayComponent.js
> +  .Dday {
요런 것은 styled-components스럽지 못합니당
styled-components의 concept 중에 하나가 "컴퍼넌트화" 인데, 결국 컴퍼넌트 이름을 가지고 뭘 하는 컴퍼넌트인지 알아보기 쉽게 하자 라는 개념이에요
그래서 요런 식으로 child component를 만들 때는 별도의 컴퍼넌트로 만드시는게 좋습니다

2021-09-10 18:06 UTC, ndaemy commented on pages/_app.js
> +      <SetGlobalStyles/>
요거는 SetGlobalStyles보다는 그냥 GlobalStyles면 어떨까요?
어차피 받아오는 쪽 파일이름도 GlobalStyles라서요!

2021-09-10 18:19 UTC, ndaemy commented on pages/index.js
> +const Theame = styled.h4`
혹시 요건 오타일까요..? 아니라면 어떤 단어인가요..?

2021-09-10 18:20 UTC, ndaemy commented on pages/index.js
> +  const [plays, setPlays] = useState([{
더미데이터처럼 setter를 사용하지 않는 변수들은 굳이 useState로 감싸실 필요 없습니다 (굳이 요거때매 풀어야 하지도 않지만요)

2021-09-10 18:20 UTC, ndaemy commented on pages/index.js
> +          {/* 클릭으로 포커스를 맞출지, 페이지 이동을 할지 미정 */}
아무래도 홈이라는 특수성을 고려했을때 저는 포커스만 맞추면 어떨까 싶은데..
다른 분들 의견도 궁금하네요

2021-09-10 18:21 UTC, ndaemy commented on pages/index.js
> +          <Theame>NEW TEAM&apos;S PLAY</Theame>
요거 굳이 저러지 않고, NEW TEAM'S PLAY 라고 하셔도 정상작동합니다

2021-09-10 18:23 UTC, ndaemy commented on pages/index.js
> +// }
next.js는 getServerSideProps라는 특수한 함수로 서버에서 데이터를 받아오잖아요?
그래서 더미데이터를 넣으실 때 여기에 넣는것도 방법입니다!
그래야 혹시 나중에 테스트 등을 붙이실 때도 더미데이터 상태에서 테스트를 붙일 수 있다는 장점이 있어요 (더 실제같은 flow기도 하구요)

2021-09-11 04:28 UTC, Bhanjo commented
넵 수정하겠습니다!

2021-09-11 15:55 UTC, Bhanjo commented on pages/index.js
> +const Theame = styled.h4`
Theme을 쓸라고 한건데 잘못썼습니다ㅎㅎ;

2021-09-11 17:28 UTC, Bhanjo commented on .prettierrc
> +}
요거는 어떤방식으로 변경하는게 좋을까요?

2021-09-23 15:10 UTC, Bhanjo commented
이제 머지 하려는데 시간나실때 approve 부탁드립니다~

2021-10-04 07:20 UTC, ndaemy requested changes

2021-10-04 07:20 UTC, ndaemy commented on .prettierrc
> +	"printWidth": 80
(8번째 줄에 코드리뷰가 안되서) 마지막에 한 줄 빈칸이요!

2021-10-04 07:20 UTC, ndaemy commented on pages/index.js
> +
(별 쓸데없는거지만) 요기 빈줄 삭제.. ㅎㅎ..

2021-10-04 07:20 UTC, ndaemy commented on components/SearchComponent.js
> +      <Background onKeyPress={handleKeyPress}>
여기는 onKeyPress보다는 form과 onSubmit을 써보시죠! (태그 자체도 의미가 있기에)
hooks를 쓰기 원하신다면 이번 기회에 [formik](https://formik.org/) 을 써보시는것도 추천드립니다

2021-10-04 07:20 UTC, ndaemy commented on components/SearchComponent.js
> +        )} */}
redirect는 정말 필요한 경우가 아니라면 패스하시는걸 추천드립니다
redirect라는게 js로 임의적으로 주소를 바꾸는 것이라, seo에서 잘 적용이 안됩니다
우리 SEO도 스터디해볼까요? ㅋㅋㅋㅋ

2021-10-04 16:06 UTC, Bhanjo commented on components/SearchComponent.js
> +        )} */}
전 당연 그쪽도 배워보고 싶긴 해요ㅋㅋㅋㅋ

2021-10-19 06:55 UTC, Bhanjo commented
home 브랜치 코드리뷰 부탁합니다!

2021-11-07 18:59 UTC, ndaemy requested changes

2021-11-07 18:59 UTC, ndaemy commented on .babelrc
> +          "ssr": true,
불필요한 스페이스가..!

2021-11-07 18:59 UTC, ndaemy commented on .prettierrc
> +  "jsxSingleQuote": true,
탭이 이상해요..!

2021-11-07 18:59 UTC, ndaemy commented on components/SearchComponent.js
> +const SearchComponent = () => {
component postfix는 쓰시지 않는게 좋아요. 말 안해도 react component이기 때문에.
차라리 SearchBar, Search 이런식으로 쓰시는게 낫슴다

2021-11-07 18:59 UTC, ndaemy commented on components/SearchComponent.js
> +`;
이거 margin-top이 의도한대로 들어가지 않는 느낌이에요 (위로 쏠려서?)
크롬 기본 margin-top 등이 있는거같은데 normalize.css 같은거로 전체적인 기본 디자인 무시하거나 하시면 편할겁니다

2021-11-07 18:59 UTC, ndaemy commented on components/PlayComponent.js
> +  width: 21.86px;
크롬 등의 브라우저에서 [소수점 이하는 씹히는 문제](http://jsfiddle.net/q5BQs/3/)가 있어요
그렇게 되면 미세하지만 원하시는대로 나오지 않을 수도 있습니다 (이정도는 괜찮다 하시면 넘어가셔도 돼요 이건)

2021-11-07 18:59 UTC, ndaemy commented on components/PlayComponent.js
> +  margin: 0 auto 11px auto;
요건 0 auto 11px 이라고 하셔도 동일한 결과가 나옵니다 ㅊㄱㅊㄱ

2021-11-07 18:59 UTC, ndaemy commented on components/SearchComponent.js
> +  );
요정도에서는 굳이 useCallback을 쓰실 필요가 없어요 [참고](https://dmitripavlutin.com/dont-overuse-react-usecallback/)

2021-11-07 18:59 UTC, ndaemy commented on components/SearchComponent.js
> +  );
오히려 잘못 쓰면 성능 저하가 생길 수도 있습니다

2021-11-07 18:59 UTC, ndaemy commented on next.config.js
> +  },
불필요한건 삭제!

2021-11-07 18:59 UTC, ndaemy commented on pages/_document.js
> +            sheet.collectStyles(<App {...props} />),
뭔가 @emotion/styled 는 이렇게까지 안복잡했던거같은데 🤔

2021-11-07 18:59 UTC, ndaemy commented on pages/_document.js
> +            sheet.collectStyles(<App {...props} />),
혹시 요거 안하면 에러 터지나요?

2021-11-07 18:59 UTC, ndaemy commented on pages/index.js
> +            </li>
여기도 map 쓰셔도 되는데! ㅋㅋㅋ

2021-11-08 08:20 UTC, Bhanjo commented on pages/_document.js
> +            sheet.collectStyles(<App {...props} />),
styled component가 페이지 렌더링 전에 적용되길래 찾아보니까 이렇게 해결한다 해서 넣었습니다..!
(https://github.com/vercel/next.js/tree/canary/examples/with-styled-components)

2021-11-09 12:15 UTC, merged